name: E2E

on: [push]

jobs:
  main:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [16, 18]

    name: Node ${{ matrix.node }} E2E

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: "recursive"
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: "pnpm"
      - uses: nrwl/nx-set-shas@v3
      - run: pnpm install
      - run: sudo apt-get install -y expect
      - run: npx playwright install --with-deps

      - name: Run tests
        uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.8
        env:
          NETLIFY_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
          TERM: xterm # fix for tput
        with:
          number-of-agents: 2
          init-commands: |
            pnpm exec nx-cloud start-ci-run --stop-agents-after="build" --agent-count=3
          parallel-commands-on-agents: |
            pnpm exec nx affected --target=e2e --parallel=2

        agents:
          name: Nx Cloud - Agents
          uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.8
          with:
            number-of-agents: 2
