name: E2E App

on: [push]

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.18.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Run App in background
        working-directory: templates/default
        run: |
          yarn install
          yarn build
          yarn start &
        env:
          PORT: 3000
      - name: Run and test app
        working-directory: templates/default
        run: |
          yarn test:e2e
        env:
          CI: true
